export const Route = {
    /**
     * Defined Internal transfer relating cache key
     */
    ROOT_URL: 'http://localhost',
    PORT: 8080,
    PREFIX: {
        ANALYTICS: '/analytics',
        CAMPAIGN: '/campaign',
        PRICE: '/price',
        MKT: '/marketing',
        EXCEL: '/excel',
    },
    API: {
        GET_TOKEN: '/get-token',
        GIVEN_TOKEN_SHOPEE: '/given-token-shopee',
        GIVEN_TOKEN_LAZADA: '/given-token-lazada',
        GIVEN_TOKEN_TIKTOK: '/given-token-tiktok',
        GET_ITEMS_TO_ELASTIC_SEARCH: '/get-items-to-elastic-search',
        GET_ITEMS_CAMPAIGN: '/get-items-campaign',
        RUN_AGGREGATION: '/run-aggregation',
        RUN_AGGREGATION_COMPOSITE: '/run-aggregation-composite',
        RUN_DETAIL_BY_SKU: '/detail-by-sku',
        GET_PRICE_FLUCTUATION_SKU: '/get-price-fluctuation-sku',
        GET_INSIDE_ORDER: '/get-inside-order',
        GET_INSIDE_ORDER_CANCEL: '/get-inside-order-cancel',
        GET_ITEMS_APP_TO_ELASTIC_SEARCH: '/get-items-app-to-elastic-search',
        GET_OFFLINE_RECEIPT: '/get-offline-receipt',
        GET_BEST_SELLER: '/get-best-seller',
        GET_TOP_300: '/get-top-300',
        GET_SKU: '/get-sku',
        EXPORT_DATA_EXCEL: '/export-data-excel',
        EXPORT_ORDER_DETAIL: '/export-order-detail',
        DOWNLOAD_EXCEL_HISTORY: '/download-excel-history',
        GET_LIST_ORDER_DETAIL: '/get-order-detail',
        GET_CAMPAIGN: '/get-campaign',
        GET_CAMPAIGN_DETAIL: '/get-campaign-detail',
        GET_CAMPAIGN_DETAIL_ORDER_STATUS: '/get-campaign-detail-order-status',
        REQUEST_EXPORT_EXCEL_CAMPAIGN_DETAIL: '/request-export-excel-campaign-detail',
        GET_PRICE_SHOPEE: '/get-price-shopee',
        GET_PRICE_LAZADA: '/get-price-lazada',
        GET_PRICE_HASAKI: '/get-price-hasaki',
        GET_PRICE_TIKTOK: '/get-price-tiktok',
        TRACKING_PERFORMANCE_SKU: '/tracking-performance-sku',
        GET_PRICE_INFO: '/get-price-info',
        EXPORT_PRICE_INFO_EXCEL: '/export-check-price',
        GET_TOKEN_FROM_GOOGLE_ADS: '/get-token-from-google-ads',
        GOOGLE_ADS_CALLBACK: '/google-ads-callback',
        GET_CAMPAIGN_GOOGLE_ADS: '/get-campaign-google-ads',
        EXPORT_TRACKING_PERFORMANCE_SKU_EXCEL: '/export-tracking-performance-sku-excel',
        TRACKING_COST_SKU: '/tracking-cost-sku',
        TRACKING_SKU_CAMPAIGN_ORDER: '/tracking-sku-campaign-order',
        DELETE_FILE_HISTORY_INDEX: '/delete-file-history-index',
        UPDATE_FILE_DOWLOAD_FAIL: '/update-file-download-fail',
        GET_PRODUCT_BY_HEALTH_AND_BEAUTY: '/get-product-by-health-and-beauty',
        GET_ALL_PRICE_INFO: '/get_all_price_info',
        PUT_MAPPING_PRICE_INFO: '/put-mapping-price-info',
        PUT_MAPPING_ANALYTICS_INFO: '/put-mapping-analytics-info',
        PUT_MAPPING_CAMPAIGN_INFO: '/put-mapping-campaign-info',
        PUT_MAPPING_HISTORY_FILE_INFO: '/put-mapping-history-file-info',
        PUT_MAX_WINDOW_PRICE_INFO: '/put-max-window-price-info',
        GET_EXCEL_HISTORYS: '/get-excel-historys',
        CHECK_EXPORT_EXCEL_PROGRESS: '/check-export-excel-progress',
        DOWNLOAD_EXCEL: '/download-excel',
        SEARCH_ES: '/search-es',
        PUT_MAPPING_SHOPPING_VIEW_INFO: '/put-mapping-shopping-view-info',
    }
}